# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='key名')),
                ('status', models.BooleanField(choices=[('1', '认证'), ('2', '未认证')], verbose_name='状态')),
            ],
            options={
                'verbose_name': 'key列表',
                'verbose_name_plural': 'key列表',
            },
        ),
    ]
