# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cmdlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdlog',
            name='ret_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='执行结果'),
        ),
    ]
