# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cmdlog_ret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdlog',
            name='ret_code',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='执行结果'),
        ),
    ]
