# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180428_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(max_length=50)),
                ('jid', models.CharField(max_length=255)),
                ('return_field', models.TextField(db_column='return')),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField()),
                ('alter_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'salt_returns',
                'managed': False,
            },
        ),
    ]
