# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_saltreturns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saltreturns',
            options={'verbose_name': 'jid记录', 'verbose_name_plural': 'jid记录'},
        ),
    ]
