# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180429_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salt_returns',
        ),
    ]
