# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_deploy_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy_model',
            old_name='deploy',
            new_name='detail',
        ),
    ]
