# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180430_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy_model',
            name='host',
        ),
    ]
