# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('下线', '下线'), ('上线', '上线')], default='正常', max_length=5, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='cloud_platform',
            name='cloud',
            field=models.CharField(blank=True, choices=[('阿里云', '阿里云'), ('腾讯云', '腾讯云'), ('其他', '其他'), ('私有云', '私有云')], max_length=20, null=True, verbose_name='云平台'),
        ),
    ]
