# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20180401_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inner_ip',
            field=models.GenericIPAddressField(verbose_name='内网管理IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='序列号'),
        ),
    ]
