# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20180401_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='disk_total',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='总磁盘'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mem_total',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='总内存'),
        ),
    ]
