# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20180407_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号'),
        ),
    ]
