# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20180407_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=30, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='序列号'),
        ),
    ]
